### ISSUE TITLE
No Longer Works with Tdrop

### ISSUE THREAD

**Issue by ibrokemypie** [vain/xiate#14]
Hey, I use xiate with a program called tdrop to use it as a dropdown terminal with a hotkey however since updating from the client-server model, it no longer seems to work, instead flashing a terminal briefly and closing instantly with no error of any kind. Theres a link to the tdrop project here, any help would be appreciated! 
https://github.com/noctuid/tdrop

**Comment by vain** [comment]
Hi,

how does your `tdrop` call look like? I just tested it with

    tdrop -ma xiate

which appears to work.

xiate v18.05 sadly renamed the binaries: You now have to use `xiate` to launch a new terminal window. Before v18.05, it used to be `xiatec`. Maybe that's the problem. :)

**Comment by ibrokemypie** [comment]
Yes, I switched the command to xiate from  xiatec. Your command doesn't work for me either, so I dont think the command is the problem, though it is `` tdrop -y 20 -x 0 -w 100% -a -m xiate`` that I use

**Comment by vain** [comment]
Hm, that works for me as well. But it's important to know that you're not trying to use tdrop's tmux mode -- this could have caused additional problems.

Which window manager are you using (I tested Openbox)? Which exact version of xiate and tdrop are you using (I tested tdrop's current git master, c3978e3)?

When you run tdrop for the first time, are there some other xiate windows already open? Or is it going to be the very first terminal window?

I just realized that tdrop has some specialized support for xiate, but it still uses `xiatec` everywhere. A wild guess: Have you tried replacing all instances of `xiatec` with `xiate` in tdrop?

It might also be worth a try to add `set -x` at the top of tdrop (second line, just below the shebang line). This will print each step that tdrop is doing. Maybe that gives us a clue.

Oh, by the way, I'm assuming that xiate runs fine without tdrop on your machine. Is that true?

**Comment by ibrokemypie** [comment]
Hmm, very odd but after a reboot and no other changes, everything works fine. Not sure if it is worth any more debugging since the issue has gone away and I don't know how to reproduce it. To answer your questions through, latest commit of both xiate and tdrop, i3-gaps, also latest commit. It was happening regardless of having other xiate windows open or not

**Comment by vain** [comment]
Odd indeed.

Well, since it works for both you and me now, I'm going to close this issue. :-)
